// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ButtonOne: typeof import('./src/components/Global/ButtonOne.vue')['default']
    ButtonTwo: typeof import('./src/components/Global/ButtonTwo.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TButton: typeof import('tdesign-vue')['Button']
    THeadMenu: typeof import('tdesign-vue')['HeadMenu']
    TMenuItem: typeof import('tdesign-vue')['MenuItem']
    TStepItem: typeof import('tdesign-vue')['StepItem']
    TSteps: typeof import('tdesign-vue')['Steps']
    TSwitch: typeof import('tdesign-vue')['Switch']
    TTag: typeof import('tdesign-vue')['Tag']
  }
}

export {}
